### ISSUE TITLE
Sourcing data

### ISSUE THREAD

**Issue by kevlened** [Lattice-Automation/repp#6]
Interesting project! I'm curious how you sourced the addgene, igem, and dnasu databases in the s3 bucket.

**Comment by jjtimmons** [comment]
Hey there and thanks! For DNASU and Addgene I reached out to them and basically just asked. There weren't (two years ago) APIs to get the data. iGEM had a data dump I used that was sufficiently recent - http://parts.igem.org/Registry_API

When making a recent update (sticking those files in S3) it occurred to me that I should confirm that those sources and others don't now have usable APIs (I don't think they do). And/or that I should reach out to update the sequences -- but I did not do that.

I find generally that both DNA repositories and DNA synthesis providers haven't bothered with making their sequences "easy to get" via APIs

**Comment by kevlened** [comment]
This is very helpful. Thanks!
